---------------------- DATETIME FONKSÝYONLARI ------------------------ 
---DATEADD // TARÝHLERÝN ÜZERÝNE ÝSTENÝLEN G,A,Y,SN EKLEMEK ÝÇÝN KULLANILIR 
DECLARE @TARIH AS DATETIME 
SET @TARIH ='2019-01-01 16:21:37'
DECLARE @TARIH2 AS DATETIME 
SET @TARIH2 = DATEADD(MONTH,6,@TARIH)
SELECT @TARIH, @TARIH2

-----DATEDIFF //TARÝHLER ARASINDA FARKI ALMAK ÝÇÝN KULLNAILIR A , Y,G OLARAK ALABÝLÝR 
DECLARE @TARIH AS DATETIME 
SET @TARIH ='2019-01-01 16:21:37'
DECLARE @TARIH2 AS DATETIME 
SET @TARIH2 = '2020-01-01 16:21:37'

SELECT DATEDIFF(MONTH,@TARIH,@TARIH2)

---- DATEFROMPARTS  // VERÝLEN TARÝHÝ FOTMATLAR 
DECLARE @TARIH AS DATETIME 
SET @TARIH=DATEFROMPARTS(2020,8,21)
SELECT @TARIH

-----DATEPART // TARÝHÝN ÝSTELÝEN KISMINI BÝZE GETÝRÝR .

DECLARE @TARIH AS DATETIME 
SET @TARIH ='2019-01-01 16:21:37'

SELECT DATEPART(HOUR,@TARIH)

--- KISA KULLANIM 
SELECT DAY (@TARIH)
SELECT YEAR (@TARIH)

--GETDATE // ANLIK SERVER TARÝHÝ GETÝRÝR . 
SELECT GETDATE()

---DOÐUM TARÝHÝ GÝRÝLEN BÝR KÝÞÝNÝN YAÞINI HESAP EDEN ÝÞLEM 
DECLARE @TARIH AS DATE
SET @TARIH ='2015-01-01'
SELECT DATEDIFF(YEAR,@TARIH,GETDATE())
