-- DATABASE ÝÞLEMÝNÝ FONKSÝYON ÝÇÝNDE KULLANMA 
-- ÜRÜN ANALÝZÝ : ÜRÜN KODU ADI EN DÜÞÜK SATIÞ FÝYATI ORT SATIÞ FÝYATI VS GELSÝN .

SELECT 
ITM.ITEMCODE AS MALZEMEKODU ,ITM.ITEMNAME MALZEMEADI,MIN(OD.UNITPRICE) AS ENDUSUKFÝYAT,
MAX(OD.UNITPRICE) AS ENYUKSEKFÝYAT , AVG(OD.UNITPRICE) AS ORTALAMAFÝYAT,
SUM(OD.LINETOTAL) AS TOPLAMSATISTUTAR , SUM(OD.AMOUNT)  AS TOPLAMSATISMÝKTARI

FROM 
ORDERDETAILS OD 
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ID
INNER JOIN USERS U ON U.ID = O.USERID
GROUP BY ITM.ITEMCODE ,ITM.ITEMNAME 

--- ÝÞLEMLERÝ FONKSÝYON ÝLE YAPALIM ::
-- SUBQUERY ÝLE YAPILIR ÝSE : 

SELECT ITM.ID, ITM.ITEMCODE  MALZEMEKODU, ITM.ITEMNAME MALZEMEADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID= ITM.ID) AS ENDUSUKFÝYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID= ITM.ID) AS ENYUKSEKFÝYAT
FROM ITEMS ITM

---- FONKSÝYON  ÝLE ::

CREATE FUNCTION DBO.GET_ITEM_MINPRICE(@ITEMID AS INT )
RETURNS FLOAT 
AS 
BEGIN 
   DECLARE @RESULT AS FLOAT 
   SELECT @RESULT = MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID -- DEÐÝÞEKNE DATASET DEN DÖNEN DEÐERÝ ATAMA 
   RETURN @RESULT  
END 

SELECT DBO.GET_ITEM_MINPRICE(84)
--------------------MAX DEÐER BULAN FUNC--------------------
CREATE FUNCTION DBO.GET_ITEM_MAXPRICE(@ITEMID AS INT )
RETURNS FLOAT 
AS 
BEGIN 
   DECLARE @RESULT AS FLOAT 
   SELECT @RESULT = MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID -- DEÐÝÞEKNE DATASET DEN DÖNEN DEÐERÝ ATAMA 
   RETURN @RESULT  
END 


--------------------TOPLAM SATISINI BULAN FUNC--------------------
CREATE FUNCTION DBO.GET_ITEM_TOTALSALE(@ITEMID AS INT )
RETURNS FLOAT 
AS 
BEGIN 
   DECLARE @RESULT AS FLOAT 
   SELECT @RESULT = SUM (LINETOTAL) FROM ORDERDETAILS OD WHERE OD.ITEMID = @ITEMID -- DEÐÝÞEKNE DATASET DEN DÖNEN DEÐERÝ ATAMA 
   RETURN @RESULT  
END 

--------------------HAZIRLANAN FONKSÝONLAR ÝLE ÝÞLEM YAPALIM 
SELECT TOP 100
ITM.ITEMCODE AS MALZEMEKODU ,ITM.ITEMNAME MALZEMEADI,
--MAX(OD.UNITPRICE) AS ENYUKSEKFÝYAT , AVG(OD.UNITPRICE) AS ORTALAMAFÝYAT,
--SUM(OD.LINETOTAL) AS TOPLAMSATISTUTAR , SUM(OD.AMOUNT)  AS TOPLAMSATISMÝKTARI
DBO.GET_ITEM_MINPRICE(ITM.ID) AS DUSUKFIYAT,
DBO.GET_ITEM_MAXPRICE(ITM.ID) AS YUKSEKFIYAT,
DBO.GET_ITEM_TOTALSALE(ITM.ID) AS SATISTUTARI

FROM  ITEMS ITM

UPDATE STATISTICS ORDERDETAILS -- SORGU PERFORMANSININ ÖLÇÜLMESÝ ÝÇÝN ÝSTATÝSTÝKLERÝ GÜNCELLEDÝK 