-- ÝÇERÝSÝNE TABLODAN DOÐUM TARÝHÝ ALIP YAÞINI BULAN FONKSÝYON 
CREATE FUNCTION DBO.CALCULATE_AGE (@BIRTHDATE AS DATETIME)
RETURNS INT 
AS BEGIN

DECLARE @RESULT AS INT 
SET @RESULT = DATEDIFF(YEAR,@BIRTHDATE,GETDATE())
RETURN @RESULT 
END 
-- FONSKÝYON DENEMESÝNÝN YAPILMASI 
SELECT DBO.CALCULATE_AGE('19910101')


-- ÝSTENÝLEN TABLODAN DOÐUM TARÝHÝ VERÝLERÝNÝN ÇEKÝLÝP YAÞ HESAPLAMASININ YAPILMASI 
SELECT TOP 1000 *,
DBO.CALCULATE_AGE(BIRTHDATE) AS KULLANICIYASI
 FROM [dbo].[USERS]