-- MÝN MAX  AVG GÝBÝ ÝÞLEM YAPAN  FAKRLI FONSKYONLARIB TEK FONSKÝYONDA TOPLANMASI 
CREATE FUNCTION DBO.GET_ITEM_PRICE(@ITEMID AS INT , @PRICETYPE AS VARCHAR(10) )
RETURNS FLOAT 
AS 
BEGIN 
DECLARE @RESULT AS FLOAT 
  IF @PRICETYPE ='MIN'
  BEGIN
  SELECT @RESULT = MIN (UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID= @ITEMID
  END 

  IF @PRICETYPE ='MAX'
  BEGIN
  SELECT @RESULT = MAX (UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID= @ITEMID
  END 

  IF @PRICETYPE ='AVG'
  BEGIN
  SELECT @RESULT = AVG (UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID= @ITEMID
  END 


  RETURN @RESULT

END 


-----------------------------FONKSÝYONU KULLANALIM
SELECT TOP 100
ITM.ITEMCODE AS MALZEMEKODU ,ITM.ITEMNAME MALZEMEADI,
DBO.GET_ITEM_PRICE(ITM.ID,'MIN') AS DUSUKFIYAT,
DBO.GET_ITEM_PRICE(ITM.ID,'MAX') AS YUKSEKFIYAT,
DBO.GET_ITEM_PRICE(ITM.ID,'AVG') AS SATISTUTARI

FROM  ITEMS ITM
