CREATE PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE  AS  DATETIME ,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT 
AS 
BEGIN 
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT 
SELECT @WORKERNAME = @WORKERNAME FROM WORKERS WHERE WORKERCODE = @WORKERBARCODE

   IF @WORKERID IS NULL 
     BEGIN 
      RAISERROR ('OKUUTLAN KART GEÇERSÝZDÝR ' ,16,1)
      RETURN 
     END 
	 --KULLANICIN SON GÝRÝÞ YAPANI BULUNDU 
       DECLARE @LASTIO AS VARCHAR(1)
       SELECT TOP 1 @LASTIO=IOTYPE  FROM WORKERTRANSECTION 
       WHERE WORKERID=1 AND DATE_>CONVERT (DATE,GETDATE())--ANLIK GÝRÝÞ BÝLGÝSÝNÝ ALDIK 
	   ORDER BY DATE_ DESC --SON GÝRÝÞ ÇIKIÞ TÜRÜ 

	   IF @LASTIO=@IOTYPE
	   BEGIN
	    IF @IOTYPE ='G'
		  BEGIN
		  RAISERROR ('ZATEN ÝÇERÝDESÝNÝZ , GÝRÝÞ YAPAMAZSINIZ ',16,1)
		  END 
	   END 

	    IF @IOTYPE ='C'
		  BEGIN
		  RAISERROR ('ZATEN DIÞARIDASINIZ  , ÇIKIÞ YAPAMAZSINIZ ',16,1)
		  END 
	   
	
	INSERT INTO WORKERTRANSECTION (WORKERID,DATE_,IOTYPE,GATEID)
	VALUES (@WORKERID ,@DATE , @IOTYPE,@GATEID)
	
	SELECT @WORKERNAME AS WORKERNAME , @DATE AS DATE_ ,@IOTYPE AS IOTYPE 
 
 END 


