------ TRÝGGER UPDATE 

CREATE TRIGGER TRG_TRANSACTION_UPDATE -- TRIGGER ÝSMÝ 
ON ITEMTRANSECTION --HANGÝ TABLO ÜZERÝNDE ÇALIÞACAK 
AFTER UPDATE       -- HANGÝ ÝÞLME ÝÇÝN TETÝKLEME YAPILACAK 
AS 
BEGIN
  DECLARE @ITEMID AS INT 
  DECLARE @OLDAMOUNT AS INT 
  DECLARE @NEWAMOUNT AS INT 
   DECLARE @AMOUNT AS INT 
  DECLARE @IOTYPE AS SMALLINT 

   SELECT @ITEMID= @ITEMID , @OLDAMOUNT= AMOUNT , @IOTYPE=IOTYPE FROM DELETED
   SELECT @NEWAMOUNT=AMOUNT FROM inserted
    SELECT @AMOUNT=@OLDAMOUNT 

	IF @IOTYPE =1
	UPDATE STOCK SET STOCK = STOCK -@AMOUNT WHERE ITEMID=@ITEMID

	IF @IOTYPE =2
	UPDATE STOCK SET STOCK = STOCK+@AMOUNT WHERE ITEMID=@ITEMID

END 

-----------------------
UPDATE [dbo].[ITEMTRANSECTION] SET AMOUNT=10 WHERE ID =3