---- TRIGGER DELETE 

CREATE TRIGGER TRG_TRANSACTION_DELETE -- TRIGGER ÝSMÝ 
ON ITEMTRANSECTION --HANGÝ TABLO ÜZERÝNDE ÇALIÞACAK 
AFTER DELETE              -- HANGÝ ÝÞLME ÝÇÝN TETÝKLEME YAPILACAK 
AS 
BEGIN
  DECLARE @ITEMID AS INT 
  DECLARE @AMOUNT AS INT 
  DECLARE @IOTYPE AS SMALLINT 

   SELECT @ITEMID= @ITEMID , @AMOUNT= AMOUNT , @IOTYPE=IOTYPE FROM DELETED

     IF @IOTYPE =1 -- GÝRÝÞ YAPILAN KAYDI SÝLMÝÞ ÝSEM  
        UPDATE STOCK SET STOCK =STOCK-@AMOUNT WHERE @ITEMID=@ITEMID -- STOCK AZLATMA ÝÞLEMÝ 
     IF @IOTYPE =2 -- ÇIKIÞ YAPILDI ÝSE 
        UPDATE STOCK SET STOCK =STOCK+@AMOUNT WHERE @ITEMID=@ITEMID --STOCK ARTIRM ÝÞLEMÝ 
END 



----------------------------------------------

-- TRÝGGER DELET TETÝKLEME 

SELECT * FROM ITEMS WHERE ID=1
SELECT * FROM [dbo].[ITEMTRANSECTION] WHERE ITEMID=1
SELECT *FROM STOCK WHERE ITEMID=1

DELETE FROM [ITEMTRANSECTION] WHERE ID =1