
SELECT ID,
(SELECT SUM (AMOUNT) FROM ITEMTRANSECTION WHERE ITEMID=ITM.ID AND IOTYPE=1) 
-
(SELECT SUM (AMOUNT) FROM ITEMTRANSECTION WHERE ITEMID=ITM.ID AND IOTYPE=2)
AS STOK
FROM ITEMS ITM 
ORDER BY ID 