---- ITEMTRANSECTION TABLOSUNA VERÝ EKLENDÝÐÝNDE STOCK TABLOSUNA VERÝ EKLEYEN TRÝGGER

CREATE TRIGGER TRG_TRANSACTION_INSERT -- TRIGGER ÝSMÝ 
ON [dbo].[ITEMTRANSECTION] --HANGÝ TABLO ÜZERÝNDE ÇALIÞACAK 
AFTER INSERT -- HANGÝ ÝÞLME ÝÇÝN TETÝKLEME YAPILACAK 
AS 
BEGIN
DECLARE @ITEMID AS INT 
DECLARE @AMOUNT AS INT 
DECLARE @IOTYPE AS SMALLINT 

SELECT @ITEMID= @ITEMID , @AMOUNT= AMOUNT , @IOTYPE=IOTYPE FROM INSERTED

  IF @IOTYPE =1 -- GÝRÝÞ YAPILDI ÝSE 
       UPDATE STOCK SET STOCK =STOCK+@AMOUNT WHERE @ITEMID=@ITEMID --
   IF @IOTYPE =2 -- GÝRÝÞ YAPILDI ÝSE 
       UPDATE STOCK SET STOCK =STOCK-@AMOUNT WHERE @ITEMID=@ITEMID --


END 


