CREATE TRIGGER TRG_ITEMS_UPDATE
ON ITEMS 
AFTER UPDATE 
AS 
BEGIN 
     INSERT INTO ITEMSLOG
	 (ID, ITEMCODE, ITEMNAME, UNITPROCE, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4,
     BRAND, LOG_ACTIONTYPE, LOG_DATE, LOG_USERNAME,LOG_PROGRAMNAME, LOG_HOSTNAME)
     SELECT ID , ITEMCODE, ITEMNAME, UNITPRICE, CATEGORY1,
     CATEGORY2, CATEGORY3, CATEGORY4, BRAND,'UPDATE', GETDATE() ,SUSER_NAME(),PROGRAM_NAME(),HOST_NAME()
	FROM  DELETED 
END 

----- GÜNCELLENEN VERÝLERÝN LOGLAMA ÝLE KAYIT ALTINA ALINMASI ÝÞLEMÝ------
  UPDATE [ETRADE].[dbo].[ITEMS] SET UNITPRICE=30 WHERE ID=6
  SELECT * FROM ITEMSLOG