-- view içinden baþka view sorgulama iþlemi 
CREATE VIEW VW_SIPARIS_DETAY
AS
SELECT  TOP 1000
U.USERNAME_ KULLANICIADI  , U.NAMESURNAME ADSOYAD ,U.TELNR1,U.TELNR2 , ITM.CATEGORY1, ITM.CATEGORY2 ,
ITM.CATEGORY3, ITM.CATEGORY4,  C.COUNTRY ULKE ,CT.CITY SEHIR ,T.TOWN ILCE , A.ADDRESSTEXT ACIKADRES
,O.ID SIPARISID ,ITM.ITEMCODE URUNKODU ,ITM.ITEMNAME  URUNADI, ITM.BRAND MARKA,
OD.AMOUNT MIKTAR, OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI ,
CONVERT(DATE,O.DATE_) AS SPARISTARIHI ,CONVERT(TIME,O.DATE_) AS SPARISZAMANI , 
DATEPART(YEAR,O.DATE_) AS YIL ,
CASE 
    WHEN DATEPART(MONTH,O.DATE_) = 1 THEN 'OCAK'
    WHEN DATEPART(MONTH,O.DATE_) = 2 THEN 'ÞUBAT'
    WHEN DATEPART(MONTH,O.DATE_) = 3 THEN 'MART'
    WHEN DATEPART(MONTH,O.DATE_) = 4 THEN 'NÝSAN'
    WHEN DATEPART(MONTH,O.DATE_) = 5 THEN 'MAYIS'
    WHEN DATEPART(MONTH,O.DATE_) = 6 THEN 'HAZÝRAN'
    WHEN DATEPART(MONTH,O.DATE_) = 7 THEN 'TEMMUZ'
    WHEN DATEPART(MONTH,O.DATE_) = 8 THEN 'AÐUSTOS'
    WHEN DATEPART(MONTH,O.DATE_) = 9 THEN 'EYLÜL'
    WHEN DATEPART(MONTH,O.DATE_) = 10 THEN 'EKÝM'
    WHEN DATEPART(MONTH,O.DATE_) = 11 THEN 'KASIM'
    WHEN DATEPART(MONTH,O.DATE_) = 12 THEN 'ARALIK'

END AS AY ,
CASE 
    WHEN DATEPART(DW,O.DATE_) = 2 THEN '2.PZT'
	WHEN DATEPART(DW,O.DATE_) = 3 THEN '3.SALI'
    WHEN DATEPART(DW,O.DATE_) = 4 THEN '4.ÇARÞAMBA'
    WHEN DATEPART(DW,O.DATE_) = 5 THEN '5.PERÞEMBE'
    WHEN DATEPART(DW,O.DATE_) = 6 THEN '6.CUMA '
    WHEN DATEPART(DW,O.DATE_) = 7 THEN '7. CUMAERESÝ'
    WHEN DATEPART(DW,O.DATE_) = 8 THEN '8 PAZAR '

   

END AS GÜN 
FROM 
ORDERDETAILS OD 
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID= O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

